version: '3.8'

services:
  # Node.js Application Service
  app:
    # Build the image from the Dockerfile located in the './src' directory
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: nodejs_mongo_app
    ports:
      - "3000:3000"
      
    # Pass configuration from the .env file to the application container
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=mongodb
      - MONGO_DATABASE=${MONGO_DATABASE}
      
    # Ensure the database container is started before the app container
    depends_on:
      - mongodb
      
    restart: unless-stopped

  # MongoDB Database Service
  mongodb:
    image: mongo:5.0
    container_name: nodejs_mongo_db
    
    # These env vars are used by the Mongo image to set up the root user
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      
    volumes:
      # This script is automatically executed by the Mongo image on first run.
      # It creates our non-root application user and database.
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # Persist MongoDB data using a named volume
      - mongo_data:/data/db
      
    restart: unless-stopped

volumes:
  mongo_data:
