# API version for Grafana provisioning
apiVersion: 1

# List of data sources to provision
datasources:
- name: Prometheus          # The name of the data source in Grafana
  type: prometheus           # The type of the data source
  access: proxy              # Access mode: 'proxy' (server-side) or 'direct' (browser-side)
  url: http://prometheus:9090 # The URL of the Prometheus container
  isDefault: true            # Set this as the default data source for new panels
  editable: true             # Allow users to edit the data source in the UI
